# Setup
title:        GDG Android Athens
tagline:      Η ελληνόφωνη ομάδα Slack περί ανάπτυξης εφαρμογών Android
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Alex Styl
  url:        http://alexstyl.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
